//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountSubstringsConsumer.CountSubstringServiceRefference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CountSubstringServiceRefference.IStringCountService")]
    public interface IStringCountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCountService/CountSubstringsInString", ReplyAction="http://tempuri.org/IStringCountService/CountSubstringsInStringResponse")]
        int CountSubstringsInString(string text, string substring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCountService/CountSubstringsInString", ReplyAction="http://tempuri.org/IStringCountService/CountSubstringsInStringResponse")]
        System.Threading.Tasks.Task<int> CountSubstringsInStringAsync(string text, string substring);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringCountServiceChannel : CountSubstringsConsumer.CountSubstringServiceRefference.IStringCountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringCountServiceClient : System.ServiceModel.ClientBase<CountSubstringsConsumer.CountSubstringServiceRefference.IStringCountService>, CountSubstringsConsumer.CountSubstringServiceRefference.IStringCountService {
        
        public StringCountServiceClient() {
        }
        
        public StringCountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringCountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountSubstringsInString(string text, string substring) {
            return base.Channel.CountSubstringsInString(text, substring);
        }
        
        public System.Threading.Tasks.Task<int> CountSubstringsInStringAsync(string text, string substring) {
            return base.Channel.CountSubstringsInStringAsync(text, substring);
        }
    }
}
